### ISSUE TITLE
 How to solve it that when I verify

### ISSUE THREAD

**Issue by shnulailai** [Levigty/AimCLR#6]
[04.26.22|13:33:35] Can not find weights [encoder_q.fc.bias].
[04.26.22|13:33:35] Can not find weights [encoder_q.fc.weight].
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    p = Processor(sys.argv[2:])
  File "/home/lailai/lailai_file/action/AimCLR/processor/processor.py", line 60, in __init__
    self.load_data()
  File "/home/lailai/lailai_file/action/AimCLR/processor/processor.py", line 92, in load_data
    dataset=train_feeder(**self.arg.train_feeder_args),
  File "/home/lailai/lailai_file/action/AimCLR/feeder/ntu_feeder.py", line 17, in __init__
    self.load_data(mmap)
  File "/home/lailai/lailai_file/action/AimCLR/feeder/ntu_feeder.py", line 22, in load_data
    self.sample_name, self.label = pickle.load(f)
_pickle.UnpicklingError: STACK_GLOBAL requires str

**Comment by czhaneva** [comment]
I think you should check your config file, and make sure the path to your dataset is right!

**Comment by Levigty** [comment]
Check the path of the dataset~

**Comment by shnulailai** [comment]
您的来信我已经收到了！
